import prisma from '../src/config/database';

const regions = [
  'Andhra Pradesh',
  'Tamil Nadu',
  'Gujarat',
  'Rajasthan',
  'West Bengal',
];

const potentialSellers = [
  // Andhra Pradesh
  {
    sellerName: 'Ramesh Reddy',
    businessName: 'Kondapalli Toys',
    phone: '9876543210',
    email: 'ramesh.kondapalli@example.com',
    address: 'Kondapalli Village, Vijayawada',
    district: 'Krishna',
    state: 'Andhra Pradesh',
    regionId: 'region-1',
    categories: ['Toys', 'Handicrafts'],
    specialization: 'Traditional wooden toys',
    giTagged: true,
    giProducts: ['Kondapalli Toys'],
    msme: true,
    msmeNumber: 'UDYAM-AP-01-1234567',
    description: 'Traditional Kondapalli wooden toy manufacturer',
    notes: 'Interested in partnership',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Lakshmi Devi',
    businessName: 'Kalamkari Arts',
    phone: '9876543211',
    email: 'lakshmi.kalamkari@example.com',
    address: 'Srikalahasti, Chittoor',
    district: 'Chittoor',
    state: 'Andhra Pradesh',
    regionId: 'region-1',
    categories: ['Textiles', 'Handloom'],
    specialization: 'Kalamkari printing',
    giTagged: true,
    giProducts: ['Kalamkari'],
    msme: false,
    description: 'Kalamkari textile printing specialist',
    notes: 'Women SHG',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Venkatesh Rao',
    businessName: 'Banjara Handicrafts',
    phone: '9876543212',
    email: 'venkatesh.banjara@example.com',
    address: 'Hyderabad',
    district: 'Hyderabad',
    state: 'Andhra Pradesh',
    regionId: 'region-1',
    categories: ['Handicrafts', 'Embroidery'],
    specialization: 'Banjara embroidery',
    giTagged: false,
    giProducts: [],
    msme: true,
    msmeNumber: 'UDYAM-AP-02-2345678',
    description: 'Traditional Banjara embroidery work',
    notes: '',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Sunita Kumari',
    businessName: 'Dhokra Crafts',
    phone: '9876543213',
    email: 'sunita.dhokra@example.com',
    address: 'Adilabad',
    district: 'Adilabad',
    state: 'Andhra Pradesh',
    regionId: 'region-1',
    categories: ['Metal Crafts', 'Handicrafts'],
    specialization: 'Dhokra metal casting',
    giTagged: false,
    giProducts: [],
    msme: false,
    description: 'Dhokra metal casting artisan',
    notes: 'Tribal artisan',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Krishna Murthy',
    businessName: 'Budithi Brass',
    phone: '9876543214',
    email: 'krishna.brass@example.com',
    address: 'Budithi Village, Srikakulam',
    district: 'Srikakulam',
    state: 'Andhra Pradesh',
    regionId: 'region-1',
    categories: ['Metal Crafts', 'Brass'],
    specialization: 'Brassware',
    giTagged: true,
    giProducts: ['Budithi Brassware'],
    msme: true,
    msmeNumber: 'UDYAM-AP-03-3456789',
    description: 'Traditional brassware manufacturer',
    notes: '',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Padma Sri',
    businessName: 'Nimmalakunta Paintings',
    phone: '9876543215',
    email: 'padma.paintings@example.com',
    address: 'Nimmalakunta, Kurnool',
    district: 'Kurnool',
    state: 'Andhra Pradesh',
    regionId: 'region-1',
    categories: ['Paintings', 'Art'],
    specialization: 'Folk paintings',
    giTagged: false,
    giProducts: [],
    msme: false,
    description: 'Traditional folk paintings',
    notes: 'Women artisan',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },

  // Tamil Nadu
  {
    sellerName: 'Karthik Sivaraman',
    businessName: 'Thanjavur Paintings',
    phone: '9876543216',
    email: 'karthik.thanjavur@example.com',
    address: 'Thanjavur',
    district: 'Thanjavur',
    state: 'Tamil Nadu',
    regionId: 'region-2',
    categories: ['Paintings', 'Art'],
    specialization: 'Thanjavur paintings',
    giTagged: true,
    giProducts: ['Thanjavur Painting'],
    msme: true,
    msmeNumber: 'UDYAM-TN-01-4567890',
    description: 'Traditional Thanjavur painting artist',
    notes: 'Family tradition',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Meenakshi Sundaram',
    businessName: 'Kanchipuram Silks',
    phone: '9876543217',
    email: 'meenakshi.silk@example.com',
    address: 'Kanchipuram',
    district: 'Kanchipuram',
    state: 'Tamil Nadu',
    regionId: 'region-2',
    categories: ['Textiles', 'Silk', 'Sarees'],
    specialization: 'Kanchipuram silk sarees',
    giTagged: true,
    giProducts: ['Kanchipuram Silk'],
    msme: true,
    msmeNumber: 'UDYAM-TN-02-5678901',
    description: 'Kanchipuram silk saree weaver',
    notes: 'Master weaver',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Rajagopal Iyer',
    businessName: 'Chola Bronzes',
    phone: '9876543218',
    email: 'rajagopal.bronze@example.com',
    address: 'Srirangam, Tiruchirappalli',
    district: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    regionId: 'region-2',
    categories: ['Metal Crafts', 'Bronze'],
    specialization: 'Chola bronze casting',
    giTagged: true,
    giProducts: ['Chola Bronze'],
    msme: true,
    msmeNumber: 'UDYAM-TN-03-6789012',
    description: 'Traditional Chola bronze sculptor',
    notes: 'Hereditary artisan',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Kavitha Rajan',
    businessName: 'Madurai Sungudi',
    phone: '9876543219',
    email: 'kavitha.sungudi@example.com',
    address: 'Madurai',
    district: 'Madurai',
    state: 'Tamil Nadu',
    regionId: 'region-2',
    categories: ['Textiles', 'Handloom'],
    specialization: 'Sungudi sarees',
    giTagged: true,
    giProducts: ['Madurai Sungudi'],
    msme: false,
    description: 'Sungudi saree weaver',
    notes: 'Women cooperative',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Subramanian Swamy',
    businessName: 'Tanjore Dolls',
    phone: '9876543220',
    email: 'subramanian.dolls@example.com',
    address: 'Thanjavur',
    district: 'Thanjavur',
    state: 'Tamil Nadu',
    regionId: 'region-2',
    categories: ['Toys', 'Handicrafts'],
    specialization: 'Thanjavur dancing dolls',
    giTagged: true,
    giProducts: ['Thanjavur Dancing Doll'],
    msme: true,
    msmeNumber: 'UDYAM-TN-04-7890123',
    description: 'Traditional Thanjavur doll maker',
    notes: '',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Lakshmi Narayanan',
    businessName: 'Kovilpatti Cotton',
    phone: '9876543221',
    email: 'lakshmi.cotton@example.com',
    address: 'Kovilpatti',
    district: 'Thoothukudi',
    state: 'Tamil Nadu',
    regionId: 'region-2',
    categories: ['Textiles', 'Cotton'],
    specialization: 'Kovilpatti cotton sarees',
    giTagged: true,
    giProducts: ['Kovilpatti Cotton'],
    msme: false,
    description: 'Kovilpatti cotton saree weaver',
    notes: 'Small scale',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },

  // Gujarat
  {
    sellerName: 'Jignesh Patel',
    businessName: 'Kutch Embroidery',
    phone: '9876543222',
    email: 'jignesh.kutch@example.com',
    address: 'Bhuj, Kutch',
    district: 'Kutch',
    state: 'Gujarat',
    regionId: 'region-3',
    categories: ['Textiles', 'Embroidery'],
    specialization: 'Kutch embroidery',
    giTagged: true,
    giProducts: ['Kutch Embroidery'],
    msme: true,
    msmeNumber: 'UDYAM-GJ-01-8901234',
    description: 'Kutch embroidery specialist',
    notes: 'Community artisan',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Bhanuben Shah',
    businessName: 'Patola Silk',
    phone: '9876543223',
    email: 'bhanuben.patola@example.com',
    address: 'Patan',
    district: 'Patan',
    state: 'Gujarat',
    regionId: 'region-3',
    categories: ['Textiles', 'Silk'],
    specialization: 'Patola sarees',
    giTagged: true,
    giProducts: ['Patola Silk'],
    msme: true,
    msmeNumber: 'UDYAM-GJ-02-9012345',
    description: 'Patola silk saree weaver',
    notes: 'Master craftsman',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Rakesh Mehta',
    businessName: 'Bandhani Textiles',
    phone: '9876543224',
    email: 'rakesh.bandhani@example.com',
    address: 'Jamnagar',
    district: 'Jamnagar',
    state: 'Gujarat',
    regionId: 'region-3',
    categories: ['Textiles', 'Tie-Dye'],
    specialization: 'Bandhani work',
    giTagged: true,
    giProducts: ['Bandhani'],
    msme: false,
    description: 'Bandhani textile artist',
    notes: '',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Chandaben Desai',
    businessName: 'Rogan Painting',
    phone: '9876543225',
    email: 'chandaben.rogan@example.com',
    address: 'Nirona, Kutch',
    district: 'Kutch',
    state: 'Gujarat',
    regionId: 'region-3',
    categories: ['Paintings', 'Textiles'],
    specialization: 'Rogan painting',
    giTagged: true,
    giProducts: ['Rogan Painting'],
    msme: false,
    description: 'Rogan painting artist',
    notes: 'Rare art form',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Dinesh Joshi',
    businessName: 'Mata ni Pachedi',
    phone: '9876543226',
    email: 'dinesh.pachedi@example.com',
    address: 'Ahmedabad',
    district: 'Ahmedabad',
    state: 'Gujarat',
    regionId: 'region-3',
    categories: ['Paintings', 'Art'],
    specialization: 'Mata ni Pachedi',
    giTagged: true,
    giProducts: ['Mata ni Pachedi'],
    msme: true,
    msmeNumber: 'UDYAM-GJ-03-0123456',
    description: 'Mata ni Pachedi painter',
    notes: 'Traditional artist',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Meenaben Parmar',
    businessName: 'Kutch Weaving',
    phone: '9876543227',
    email: 'meenaben.weaving@example.com',
    address: 'Bhuj, Kutch',
    district: 'Kutch',
    state: 'Gujarat',
    regionId: 'region-3',
    categories: ['Textiles', 'Handloom'],
    specialization: 'Kutch weaving',
    giTagged: false,
    giProducts: [],
    msme: false,
    description: 'Kutch handloom weaver',
    notes: 'Women artisan',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },

  // Rajasthan
  {
    sellerName: 'Gopal Singh',
    businessName: 'Jaipur Block Print',
    phone: '9876543228',
    email: 'gopal.blockprint@example.com',
    address: 'Jaipur',
    district: 'Jaipur',
    state: 'Rajasthan',
    regionId: 'region-4',
    categories: ['Textiles', 'Block Print'],
    specialization: 'Jaipur block printing',
    giTagged: true,
    giProducts: ['Jaipur Block Print'],
    msme: true,
    msmeNumber: 'UDYAM-RJ-01-1234567',
    description: 'Jaipur block printing specialist',
    notes: 'Traditional craft',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Suman Devi',
    businessName: 'Kota Doria Sarees',
    phone: '9876543229',
    email: 'suman.kota@example.com',
    address: 'Kota',
    district: 'Kota',
    state: 'Rajasthan',
    regionId: 'region-4',
    categories: ['Textiles', 'Sarees'],
    specialization: 'Kota Doria sarees',
    giTagged: true,
    giProducts: ['Kota Doria'],
    msme: false,
    description: 'Kota Doria saree weaver',
    notes: 'Women cooperative',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Ramesh Kumar',
    businessName: 'Jodhpur Juti',
    phone: '9876543230',
    email: 'ramesh.juti@example.com',
    address: 'Jodhpur',
    district: 'Jodhpur',
    state: 'Rajasthan',
    regionId: 'region-4',
    categories: ['Footwear', 'Handicrafts'],
    specialization: 'Jodhpuri jutis',
    giTagged: true,
    giProducts: ['Jodhpuri Juti'],
    msme: true,
    msmeNumber: 'UDYAM-RJ-02-2345678',
    description: 'Jodhpuri juti maker',
    notes: 'Family business',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Kamlesh Sharma',
    businessName: 'Udaipur Miniature',
    phone: '9876543231',
    email: 'kamlesh.miniature@example.com',
    address: 'Udaipur',
    district: 'Udaipur',
    state: 'Rajasthan',
    regionId: 'region-4',
    categories: ['Paintings', 'Art'],
    specialization: 'Udaipur miniature paintings',
    giTagged: true,
    giProducts: ['Udaipur Miniature'],
    msme: true,
    msmeNumber: 'UDYAM-RJ-03-3456789',
    description: 'Udaipur miniature painting artist',
    notes: 'Master artist',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Rekha Kumari',
    businessName: 'Leheriya Textiles',
    phone: '9876543232',
    email: 'rekha.leheriya@example.com',
    address: 'Jaipur',
    district: 'Jaipur',
    state: 'Rajasthan',
    regionId: 'region-4',
    categories: ['Textiles', 'Tie-Dye'],
    specialization: 'Leheriya work',
    giTagged: true,
    giProducts: ['Leheriya'],
    msme: false,
    description: 'Leheriya textile artist',
    notes: 'Women artisan',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Mahendra Singh',
    businessName: 'Blue Pottery',
    phone: '9876543233',
    email: 'mahendra.pottery@example.com',
    address: 'Jaipur',
    district: 'Jaipur',
    state: 'Rajasthan',
    regionId: 'region-4',
    categories: ['Pottery', 'Handicrafts'],
    specialization: 'Blue pottery',
    giTagged: true,
    giProducts: ['Jaipur Blue Pottery'],
    msme: true,
    msmeNumber: 'UDYAM-RJ-04-4567890',
    description: 'Blue pottery artisan',
    notes: 'Traditional craft',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },

  // West Bengal
  {
    sellerName: 'Amit Das',
    businessName: 'Kantha Embroidery',
    phone: '9876543234',
    email: 'amit.kantha@example.com',
    address: 'Kolkata',
    district: 'Kolkata',
    state: 'West Bengal',
    regionId: 'region-5',
    categories: ['Textiles', 'Embroidery'],
    specialization: 'Kantha embroidery',
    giTagged: true,
    giProducts: ['Kantha Embroidery'],
    msme: true,
    msmeNumber: 'UDYAM-WB-01-5678901',
    description: 'Kantha embroidery specialist',
    notes: 'Traditional craft',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Priya Mukherjee',
    businessName: 'Baluchari Sarees',
    phone: '9876543235',
    email: 'priya.baluchari@example.com',
    address: 'Bishnupur, Bankura',
    district: 'Bankura',
    state: 'West Bengal',
    regionId: 'region-5',
    categories: ['Textiles', 'Sarees'],
    specialization: 'Baluchari sarees',
    giTagged: true,
    giProducts: ['Baluchari Saree'],
    msme: false,
    description: 'Baluchari saree weaver',
    notes: 'Women cooperative',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Subrata Ghosh',
    businessName: 'Terracotta Crafts',
    phone: '9876543236',
    email: 'subrata.terracotta@example.com',
    address: 'Bishnupur, Bankura',
    district: 'Bankura',
    state: 'West Bengal',
    regionId: 'region-5',
    categories: ['Pottery', 'Handicrafts'],
    specialization: 'Terracotta crafts',
    giTagged: true,
    giProducts: ['Bankura Terracotta'],
    msme: true,
    msmeNumber: 'UDYAM-WB-02-6789012',
    description: 'Terracotta craft specialist',
    notes: 'Traditional artisan',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Anjali Sen',
    businessName: 'Tant Sarees',
    phone: '9876543237',
    email: 'anjali.tant@example.com',
    address: 'Shantipur, Nadia',
    district: 'Nadia',
    state: 'West Bengal',
    regionId: 'region-5',
    categories: ['Textiles', 'Handloom'],
    specialization: 'Tant sarees',
    giTagged: true,
    giProducts: ['Tant Saree'],
    msme: false,
    description: 'Tant saree weaver',
    notes: 'Women artisan',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Rajib Roy',
    businessName: 'Chau Masks',
    phone: '9876543238',
    email: 'rajib.chau@example.com',
    address: 'Purulia',
    district: 'Purulia',
    state: 'West Bengal',
    regionId: 'region-5',
    categories: ['Masks', 'Handicrafts'],
    specialization: 'Chau masks',
    giTagged: true,
    giProducts: ['Chau Mask'],
    msme: true,
    msmeNumber: 'UDYAM-WB-03-7890123',
    description: 'Chau mask maker',
    notes: 'Traditional craft',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
  {
    sellerName: 'Madhumita Bose',
    businessName: 'Jamdani Sarees',
    phone: '9876543239',
    email: 'madhumita.jamdani@example.com',
    address: 'Dhaniakhali, Hooghly',
    district: 'Hooghly',
    state: 'West Bengal',
    regionId: 'region-5',
    categories: ['Textiles', 'Sarees'],
    specialization: 'Jamdani sarees',
    giTagged: true,
    giProducts: ['Jamdani Saree'],
    msme: false,
    description: 'Jamdani saree weaver',
    notes: 'Master weaver',
    source: 'Manual Entry',
    status: 'NOT_CONTACTED',
  },
];

async function main() {
  console.log('Starting seed of potential sellers...');

  // Get existing regions
  const existingRegions = await (prisma as any).region.findMany();
  
  if (existingRegions.length === 0) {
    console.log('No regions found. Please seed regions first.');
    return;
  }

  // Map region names to IDs
  const regionMap = new Map(
    existingRegions.map((r: any) => [r.name, r.id])
  );

  let created = 0;
  let skipped = 0;

  for (const seller of potentialSellers) {
    const regionId = regionMap.get(regions[potentialSellers.indexOf(seller) % regions.length]);
    
    if (!regionId) {
      console.log(`Skipping ${seller.businessName} - region not found`);
      skipped++;
      continue;
    }

    try {
      await (prisma as any).potentialSeller.create({
        data: {
          ...seller,
          regionId,
        },
      });
      created++;
      console.log(`Created: ${seller.businessName}`);
    } catch (error) {
      console.log(`Skipped ${seller.businessName} - likely duplicate`);
      skipped++;
    }
  }

  console.log(`\nSeed completed!`);
  console.log(`Created: ${created} potential sellers`);
  console.log(`Skipped: ${skipped} potential sellers`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
